/** Autogenerated Main.cpp. */

#include <JuceHeader.h>
#include "includes.h"

// ==================================| Project Factory |==================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -----------------------------------------------------------
		
		registerPolyNode<project::loopenv<1>, wrap::illegal_poly<project::loopenv<1>>>();
		registerPolyNode<project::seq<1>, wrap::illegal_poly<project::seq<1>>>();
	}
};
}

project::Factory f;

// ==============================| Exported DLL functions |==============================

DLL_EXPORT int getNumNodes()
{
	return f.getNumNodes();
}

DLL_EXPORT size_t getNodeId(int index, char* t)
{
	return HelperFunctions::writeString(t, f.getId(index).getCharPointer());
}

DLL_EXPORT int getNumDataObjects(int nodeIndex, int dataTypeAsInt)
{
	return f.getNumDataObjects(nodeIndex, dataTypeAsInt);
}

DLL_EXPORT void deInitOpaqueNode(scriptnode::OpaqueNode* n)
{
	n->callDestructor();
}

DLL_EXPORT void initOpaqueNode(scriptnode::OpaqueNode* n, int index, bool polyIfPossible)
{
	f.initOpaqueNode(n, index, polyIfPossible);
}
DLL_EXPORT int getHash(int index)
{
	static const int hashIndexes[2] =
	{
		0,
		-372561236
	};
	return hashIndexes[index];
}
DLL_EXPORT int getWrapperType(int index)
{
	return f.getWrapperType(index);
}
DLL_EXPORT scriptnode::Error getError()
{
	return f.getError();
}
DLL_EXPORT void clearError()
{
	f.clearError();
}

