#!/bin/bash
PATH="/usr/local/bin:$PATH"
chmod +x "/Users/rick/Documents/GitHub/HISE/JUCE/Projucer/Projucer.app/Contents/MacOS/Projucer"
cd "`dirname "$0"`"
"/Users/rick/Documents/GitHub/HISE/JUCE/Projucer/Projucer.app/Contents/MacOS/Projucer" --resave AutogeneratedProject.jucer

set -o pipefail
echo Compiling  oi grandad ...
xcodebuild -project "Builds/MacOSX/oi grandad.xcodeproj" -configuration "Release" -jobs "10" | "/Users/rick/Documents/GitHub/HISE/tools/Projucer/xcbeautify"
