/** Autogenerated Main.cpp. */

#include <JuceHeader.h>
#include "includes.h"

// =====================================| Project Factory |=====================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -----------------------------------------------------------------
		
		registerDataNode<project::balancefx_networkdata>();
		registerDataNode<project::delverb_networkdata>();
		registerDataNode<project::gran2_networkdata>();
		registerDataNode<project::LoopAR_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

