/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::master_bus_compressor_native<1>, scriptnode::wrap::illegal_poly<project::master_bus_compressor_native<1>>>();
		registerPolyNode<project::granular_player_stepquant_density_hybrid_native<1>, project::granular_player_stepquant_density_hybrid_native<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::DspNetwork<1>, wrap::illegal_poly<project::DspNetwork<1>>>();
		registerPolyNode<project::ENV<1>, project::ENV<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::MacroMod<1>, project::MacroMod<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::MatrixTest2<1>, project::MatrixTest2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::OutMods<1>, wrap::illegal_poly<project::OutMods<1>>>();
		registerPolyNode<project::res2<1>, project::res2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::sn_fin<1>, wrap::illegal_poly<project::sn_fin<1>>>();
		registerPolyNode<project::vecfade<1>, wrap::illegal_poly<project::vecfade<1>>>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::Dyn_networkdata>();
		registerDataNode<project::FoldTests_networkdata>();
		registerDataNode<project::FreshNetwork_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::ggg_networkdata>();
		registerDataNode<project::grangran_networkdata>();
		registerDataNode<project::gtest_networkdata>();
		registerDataNode<project::MatrixTest_networkdata>();
		registerDataNode<project::modcont_networkdata>();
		registerDataNode<project::ModNew_networkdata>();
		registerDataNode<project::NuTest_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::recorder_networkdata>();
		registerDataNode<project::slotty_networkdata>();
		registerDataNode<project::sn_networkdata>();
		registerDataNode<project::sndummy_networkdata>();
		registerDataNode<project::SpreadExample_networkdata>();
		registerDataNode<project::test_networkdata>();
		registerDataNode<project::track_networkdata>();
		registerDataNode<project::trash2_networkdata>();
		registerDataNode<project::vec1b_networkdata>();
		registerDataNode<project::vec2b_networkdata>();
		registerDataNode<project::vec3_networkdata>();
		registerDataNode<project::vec4_networkdata>();
	}
};

#if HISE_INCLUDE_RT_NEURAL

struct NeuralFactory: public hise::NeuralNetwork::Factory
{
	NeuralFactory()
	{
	}
	void* cloneModel(void* model) const
	{
		if(auto m = static_cast<hise::NeuralNetwork::ModelBase*>(model))
		{
			return m->clone();
		}
		return nullptr;
	}
	void destroyModel(void* model) const
	{
		delete static_cast<hise::NeuralNetwork::ModelBase*>(model);
	}
	void resetModel(void* model) const
	{
		if(auto m = static_cast<hise::NeuralNetwork::ModelBase*>(model))
		{
			m->reset();
		}
	}
	void processModel(void* model, const float* input, float* output) const
	{
		if(auto m = static_cast<hise::NeuralNetwork::ModelBase*>(model))
		{
			m->process(input, output);
		}
	}
};
#endif
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if HISE_INCLUDE_RT_NEURAL
void scriptnode::DspNetwork::registerStaticNeuralNetworks(hise::NeuralNetwork::Factory* f)
{
}
#endif

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


