/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files ------------------

#include "DspNetwork.h"
#include "MacroMod.h"
#include "modcont_networkdata.h"
#include "OutMods_networkdata.h"
#include "res2.h"
#include "sn.h"
#include "sndummy_networkdata.h"
#include "track_networkdata.h"
#include "vec1b_networkdata.h"
#include "vec2b_networkdata.h"
#include "vec3_networkdata.h"
#include "vec4_networkdata.h"
#include "vecfade_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

