/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files ------------------

#include "ana1_networkdata.h"
#include "Ana2_networkdata.h"
#include "ana3_networkdata.h"
#include "ana4_networkdata.h"
#include "analyise_networkdata.h"
#include "buff_networkdata.h"
#include "DspNetwork.h"
#include "g1stack_networkdata.h"
#include "grainF_networkdata.h"
#include "GranularWithMod_networkdata.h"
#include "Gr_networkdata.h"
#include "gt2244_networkdata.h"
#include "Hole_networkdata.h"
#include "k_networkdata.h"
#include "MacroMod.h"
#include "min_networkdata.h"
#include "modcont_networkdata.h"
#include "ng_networkdata.h"
#include "OutMods_networkdata.h"
#include "pb_networkdata.h"
#include "pitch_networkdata.h"
#include "record_networkdata.h"
#include "res1_networkdata.h"
#include "res2.h"
#include "sn.h"
#include "track2_networkdata.h"
#include "track3_networkdata.h"
#include "track4_networkdata.h"
#include "TrackIn2_networkdata.h"
#include "track_networkdata.h"
#include "TrkIn1_networkdata.h"
#include "trkin3_networkdata.h"
#include "Trkin4_networkdata.h"
#include "vec1b_networkdata.h"
#include "vec2b_networkdata.h"
#include "vec3_networkdata.h"
#include "vec4_networkdata.h"
#include "vecfade_networkdata.h"
#include "vrtb_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

