/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ------------------------

#include "granular_player_stepquant_density_hybrid_native.h"

// Include compiled network files --------------------------

#include "DspNetwork.h"
#include "MacroMod.h"
#include "OutMods.h"
#include "res2.h"
#include "sn.h"
#include "sndummy.h"
#include "sn_fin.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

